title: Pierrick Jeanjean
email: pierrick.jeanjean@gmail.com
description: Personal blog
baseurl: ""
url: ""
twitter_username: 
github_username:
permalink: /:categories/:title/

collections:
  categories:
    output: true
  tags:
    output: true

# Build settings
theme: minima
plugins:
  - jekyll-feed