title: Pierrick Jeanjean
email: pierrick.jeanjean@gmail.com
description: Daily use blog for writing down what I learned (coding, recipes, travels, ...) and more to come! 
baseurl: ""
url: ""
twitter_username: 
github_username:
permalink: /:categories/:title/

show_excerpts: true

collections:
  categories:
    output: true
  tags:
    output: true

# Build settings
theme: minima
plugins:
  - jekyll-feed