title: Pierrick Jeanjean
email: pierrick.jeanjean@gmail.com
description: Personal blog
baseurl: ""
url: ""
twitter_username: 
github_username:
permalink: /:categories/:title/

# Build settings
theme: minima
plugins:
  - jekyll-feed