title: Pierrick Jeanjean

baseurl: ""
url: ""

author: 
  name: Pierrick Jeanjean
  email: pierrick.jeanjean@gmail.com

permalink: /:categories/:title/
collections:
  categories:
    output: true
  tags:
    output: true

show_excerpts: true

# Build settings
theme: minima
plugins:
  - jekyll-feed